id           = "yogaeru/mango_layout"
name         = "Mango Layout Switcher"
version      = "1.0.1"
min_noctalia = "5.0.0"
author       = "yogaeru"
license      = "MIT"
plugin_api   = 14
icon         = "layout-filled"
description  = "Layout switcher for MangoWC"

[[setting]]
key             = "close_on_select"
type            = "bool"
label_key       = "settings.close_on_select.label"
description_key = "settings.close_on_select.description"
default         = false

[[setting]]
key             = "compact_label"
type            = "bool"
label_key       = "settings.compact_label.label"
description_key = "settings.compact_label.description"
default         = false

[[widget]]
id = "mango_layout"
entry = "widget.luau"

  [[widget.setting]]
  key             = "dynamic_icon"
  type            = "bool"
  label_key       = "settings.dynamic_icon.label"
  description_key = "settings.dynamic_icon.description"
  default         = false
  
  [[widget.setting]]
  key             = "icon"
  type            = "glyph"
  label_key       = "settings.icon.label"
  description_key = "settings.icon.description"
  default         = "layout-filled"
  visible_when    = { key = "dynamic_icon", values = ["false"] }

[[panel]]
id = "main"
entry = "panel.luau"
width = 420
height = 410
placement = "floating"
position = "center"


